### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takken08** [takken08/furima-37728#22]
#URL
https://furima-37728.herokuapp.com/

#Basic認証のIDとパスワード
ID: take
password: 0814

#出品者用のメールアドレスとパスワード
mail: test@test
password: test123

#購入者用のメールアドレスとパスワード
mail: test@test2
password: test123

**Comment by shodai-ito** [comment]
@takken08 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`商品出品機能`**
- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
表示される都道府県には「県」も含めましょう。
<img width="425" alt="スクリーンショット 2022-08-14 9 28 51" src="https://user-images.githubusercontent.com/62537107/184517821-e06d269a-b3de-4155-96dd-04664bc8a3eb.png">

- [x] **発送までの日数は、「---、1~2日で発送、2~3日で発送、4~7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
表示される日付の範囲を見本アプリと揃えましょう！
<img width="370" alt="スクリーンショット 2022-08-14 9 28 39" src="https://user-images.githubusercontent.com/62537107/184517834-5bf8cad3-f793-4a41-84b2-4a23b0724777.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by soll02solglas** [comment]
@takken08 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/curriculums/7106

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![lgtm_01](https://user-images.githubusercontent.com/30042165/184563327-f8646094-6426-4f8e-9108-1680b6392e36.png)
